### ISSUE TITLE
photos

### ISSUE THREAD

**Issue by xudafeng** [macacajs/macaca-products-design#1]
---

**Comment by zhuyali** [comment]
![2](https://cloud.githubusercontent.com/assets/15025212/20209812/4f2e140c-a831-11e6-8084-06f70588fd60.jpg)
![3](https://cloud.githubusercontent.com/assets/15025212/20209814/4f7e6132-a831-11e6-84dd-d8ab757b7595.jpg)
![4](https://cloud.githubusercontent.com/assets/15025212/20209813/4f2fbf1e-a831-11e6-8934-c07229cdada0.jpg)

**Comment by xudafeng** [comment]
![1](https://cloud.githubusercontent.com/assets/1011681/20209944/067c7cca-a832-11e6-8a19-22647420a5c3.jpg)
